name: GitHub Pages 배포

on:
  push:
    branches:
      - main  # 메인 브랜치 푸시시 실행
  workflow_run:
    workflows: ["일일 크롤링 및 RSS 업데이트"]
    types:
      - completed

permissions:
  contents: write  # 저장소에 쓰기 권한 부여

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 전체 히스토리 가져오기

      - name: feeds 디렉토리 확인
        run: |
          mkdir -p feeds
          touch feeds/.gitkeep

      - name: GitHub Pages 배포
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          commit_message: "Deploy: ${{ github.event.head_commit.message }}" 