name: "월간 학사일정 업데이트"

on:
  schedule:
    - cron: "10 0 1 * *"  # 매월 1일 00:10 UTC (한국시간 09:10)
  workflow_dispatch:

jobs:
  update-schedule:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3
      
      - name: Python 환경 설정
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      
      - name: 의존성 설치
        working-directory: ./school_notice_crawl
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: 학사일정 크롤링
        working-directory: ./school_notice_crawl
        run: |
          cd src
          python school_schedule_crawler.py
      
      - name: 변경 내용 커밋
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add school_notice_crawl/school_schedule.html
          git commit -m "월간 학사일정 자동 업데이트 $(date +'%Y-%m-%d')" || echo "No changes to commit"
      
      - name: 변경 내용 푸시
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }} 