---
name: "주간 급식 정보 업데이트"

on:
  schedule:
    - cron: "0 0 * * 0"  # 매주 일요일 UTC 00:00 (한국 시간 09:00)
  workflow_dispatch:

jobs:
  update-meal:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3
      
      - name: Python 환경 설정
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      
      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: 급식 정보 크롤링
        run: |
          python src/meal_crawler.py
      
      - name: 변경 내용 커밋
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add meal_info.html
          git commit -m "주간 급식 정보 업데이트 $(date +'%Y-%m-%d')" || echo "No changes to commit"
      
      - name: 변경 내용 푸시
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }} 